# Site settings
title: Vishnu Vardhan Reddy
email: samanthula.v@northeastern.edu
description: >-
  Backend Developer specializing in distributed systems, blockchain, 
  and data analytics. MS in Data Analytics at Northeastern University.
baseurl: ""
url: "https://vishnu2505.github.io"
repository_url: "https://github.com/vishnu2505/vishnu2505.github.io"

# Social
github_username: vishnu2505
linkedin_username: "https://www.linkedin.com/in/vishnu-vardhan-reddy-samanthula-056a831b6/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"